#  ███╗   ███╗██╗   ██╗██████╗ ███████╗██████╗ ███╗   ███╗███████╗
#  ████╗ ████║╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗████╗ ████║██╔════╝
#  ██╔████╔██║ ╚████╔╝ ██████╔╝█████╗  ██████╔╝██╔████╔██║███████╗
#  ██║╚██╔╝██║  ╚██╔╝  ██╔═══╝ ██╔══╝  ██╔══██╗██║╚██╔╝██║╚════██║
#  ██║ ╚═╝ ██║   ██║   ██║     ███████╗██║  ██║██║ ╚═╝ ██║███████║
#  ╚═╝     ╚═╝   ╚═╝   ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
# #####################################***************************
#######
#### Turning this option on will make myPerms use only one world
### of specification for all worlds within the server.
### Make sure the "world" section has the world you intend to use if you
### wish to enable this feature.
global:
  ignore-world-container: false
  world: world