#   ___  ___   ________   _______    ________   _____ ______    ________
#  |\  \|\  \ |\   __  \ |\  ___ \  |\   __  \ |\   _ \  _   \ |\   ____\
#  \ \  \\\  \\ \  \|\  \\ \   __/| \ \  \|\  \\ \  \\\__\ \  \\ \  \___|_
#   \ \   __  \\ \   ____\\ \  \_|/__\ \   _  _\\ \  \\|__| \  \\ \_____  \
#    \ \  \ \  \\ \  \___| \ \  \_|\ \\ \  \\  \|\ \  \    \ \  \\|____|\  \
#     \ \__\ \__\\ \__\     \ \_______\\ \__\\ _\ \ \__\    \ \__\ ____\_\  \
#      \|__|\|__| \|__|      \|_______| \|__|\|__| \|__|     \|__||\_________\
#               By: Hempfest                                      \|_________|
# =============================================================================
#######
#### Turning this option on will make hPermissions use only one world
### of specification for all worlds within the server.
### Make sure the "world" section has the world you intend to use if you
### wish to enable this feature.
global:
  ignore-world-container: false
  world: world