name: hPermissions
version: 2.0.0
author: Hempfest
api-version: 1.13
depend: [ Labyrinth ]
soft-depend: [ Vault ]
description: A SuperPerms and Vault compatible permissions system.
main: com.youtube.hempfest.permissions.HempfestPermissions